### ISSUE TITLE
ring-mock 0.3.0 drops DELETE body

### ISSUE THREAD

**Issue by ergl** [ring-clojure/ring-mock#8]
Hi!

It seems that the newest version of ring-mock ("0.3.0") no longer accepts a body
in a DELETE request?

I have some API here that I would like to test which requires to pass along
content as the body of a DELETE request. Sadly that doesn't work right now in
the latest version.

The http spec doesn't disallow having a body in the request, although it warns
that some servers may ignore it. (Jetty, the one I'm using, doesn't ignore it).

As per [http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19)

>Bodies on DELETE requests have no defined semantics.  Note that sending a body
on a DELETE request might cause some existing implementations to reject the
request.

Also see this [stackoverflow answer](http://stackoverflow.com/a/299696).

>an _entity-body_ is explicitly forbidden in TRACE requests only, **all other
request types are unrestricted** (section 9, and 9.8 specifically)

(emphasis mine)

Seems like this was introduced in 38471fa09b1106df25c95973a1fb836f696a861c

As it stands, this seems like a decision that should be done by the server
(e.g Jetty) rather than by the client (this library).

Is there any hope in this being changed back to the original implementation?

If not, at least this should be noted somewhere in the documentation.

**Comment by weavejester** [comment]
This was added in pull request #2. However it's not true that DELETE requests no longer accept a body; only that the default behaviour for parameters attached to a DELETE request is to add them to the query string, rather than encode them in the body.

The reason for this change is that, as you point out, DELETE requests have no defined semantics for their bodies. Because they have no defined semantics, it doesn't make sense for parameters to be placed in the body *by default*, as they would with a POST or PUT.

If you do want to add parameters to the body of a DELETE request, you still can, you just need to be explicit about what you want:

```clojure
(-> (request :delete "/foo")
    (body {:foo "bar"}))
```

**Comment by ergl** [comment]
That sounds fair! — thanks for letting me know how to do the right way
